/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.partials.canvas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fetch_002dparameters_002ddialog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<div id=\"fetch-parameters-dialog\" layout=\"column\" class=\"hidden large-dialog\">\n    <div id=\"fetch-parameters-status-bar\"></div>\n    <div class=\"dialog-content\">\n        ");
      out.write("\n        <div class=\"settings-left\">\n            <div id=\"fetch-parameters-provider-groups-container\" class=\"setting\">\n                <div class=\"setting-name\">Name</div>\n                <div class=\"setting-field\">\n                    <span id=\"fetch-parameters-id\" class=\"hidden\"></span>\n                    <div id=\"fetch-parameters-name\"></div>\n                    <div class=\"clear\"></div>\n                </div>\n            </div>\n            <div id=\"fetch-parameters-usage-container\" class=\"setting\">\n                <div class=\"setting-name\">\n                    Select to configure a parameter group\n                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Discovered parameter groups from this parameter provider. Select a group to create a parameter context, then configure its parameter sensitivities.\"></div>\n                </div>\n                <div id=\"parameter-groups-table\"></div>\n            </div>\n            <div id=\"apply-groups-container\" class=\"setting hidden\">\n                <div class=\"setting-name\">Parameter Groups</div>\n");
      out.write("                <div class=\"setting-field\">\n                    <div id=\"apply-groups-list\"></div>\n                </div>\n            </div>\n        </div>\n        ");
      out.write("\n\n        <div class=\"spacer\">&nbsp;</div>\n\n        ");
      out.write("\n        <div class=\"settings-center\">\n            <div id=\"parameters-container\" class=\"setting\">\n                <div id=\"create-parameter-context-checkbox-container\" class=\"setting-field\"></div>\n                <div id=\"fetched-parameters-container\" class=\"setting\">\n                    <div class=\"setting-name\">\n                        Fetched parameters\n                        <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Discovered parameters from the selected parameter group.\"></div>\n                    </div>\n                    <div id=\"fetched-parameters-listing-container\" class=\"setting-field\">\n                        <ol id=\"fetched-parameters-listing\"></ol>\n                    </div>\n                </div>\n                <div id=\"selectable-parameters-container\" class=\"setting\">\n                    <div class=\"setting-name\">\n                        Select parameters to be set as sensitive\n                        <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Only parameters that are not referenced can be modified.\"></div>\n");
      out.write("                    </div>\n                    <div id=\"selectable-parameters-buttons\">\n                        <button id=\"select-all-fetched-parameters\" class=\"selectable-parameters-buttons\">\n                            <div class=\"fa fa-check-square-o\"></div>\n                            <span>Select all</span>\n                        </button>\n                        <button id=\"deselect-all-fetched-parameters\" class=\"selectable-parameters-buttons\">\n                            <div class=\"fa fa-minus-square-o\"></div>\n                            <span>Deselect all</span>\n                        </button>\n                        <div class=\"clear\"></div>\n                    </div>\n                    <div id=\"selectable-parameters-table\" class=\"setting-field\"></div>\n                </div>\n            </div>\n            <div id=\"fetch-parameters-update-status-container\" class=\"setting\">\n                <div id=\"fetch-parameters-update-status\" class=\"hidden\">\n                    <div class=\"setting\">\n                        <div class=\"setting-name\">\n");
      out.write("                            Steps to update parameters\n                        </div>\n                        <div class=\"setting-field\">\n                            <ol id=\"fetch-parameters-update-steps\"></ol>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n        ");
      out.write("\n\n        <div class=\"spacer\">&nbsp;</div>\n\n        ");
      out.write("\n        <div class=\"settings-right\">\n            <div class=\"setting\">\n                <div class=\"setting-name\">\n                    Parameter Contexts To Create\n                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Parameter groups set to be created as parameter contexts, pending apply.\"></div>\n                </div>\n                <div class=\"setting-field\">\n                    <div id=\"parameter-contexts-to-create-container\" class=\"ellipsis\"></div>\n                </div>\n            </div>\n            <div class=\"setting\">\n                <div class=\"setting-name\">\n                    Parameter Contexts To Update\n                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Synced parameter contexts to be updated, pending apply.\"></div>\n                    <div class=\"referencing-components-loading\"></div>\n                </div>\n                <div class=\"setting-field\">\n                    <div id=\"parameter-contexts-to-update-container\" class=\"ellipsis\"></div>\n                </div>\n");
      out.write("            </div>\n\n            <div id=\"fetch-parameters-referencing-components-container\" class=\"setting hidden\">\n                <div class=\"setting-name\">\n                    Referencing Components\n                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Components referencing this selected parameter.\"></div>\n                    <div class=\"referencing-components-loading\"></div>\n                </div>\n                <div id=\"fetch-parameter-referencing-components-container\" class=\"setting-field\">\n                </div>\n            </div>\n            <div id=\"fetch-parameters-referencing-components-template\" class=\"fetch-parameters-referencing-components-template hidden clear\">\n                <div class=\"setting\">\n                    <div class=\"setting-name\">Referencing Processors\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-processors\"></ul>\n                    </div>\n                </div>\n                <div class=\"setting\">\n");
      out.write("                    <div class=\"setting-name\">\n                        Referencing Controller Services\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-controller-services\"></ul>\n                    </div>\n                </div>\n                <div class=\"setting\">\n                    <div class=\"setting-name\">\n                        Unauthorized referencing components\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-unauthorized-components\"></ul>\n                    </div>\n                </div>\n            </div>\n\n            <div id=\"fetch-parameters-affected-referencing-components-container\" class=\"setting\">\n                <div class=\"setting-name\">\n                    Affected Referencing Components\n                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Affected components referencing this parameter provider.\"></div>\n");
      out.write("                    <div class=\"referencing-components-loading\"></div>\n                </div>\n                <div id=\"affected-referencing-components-container\" class=\"setting-field\">\n                </div>\n            </div>\n            <div id=\"affected-referencing-components-template\" class=\"affected-referencing-components-template hidden clear\">\n                <div class=\"setting\">\n                    <div class=\"setting-name\">Referencing Processors\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-processors\"></ul>\n                    </div>\n                </div>\n                <div class=\"setting\">\n                    <div class=\"setting-name\">\n                        Referencing Controller Services\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-controller-services\"></ul>\n                    </div>\n                </div>\n                <div class=\"setting\">\n");
      out.write("                    <div class=\"setting-name\">\n                        Unauthorized referencing components\n                    </div>\n                    <div class=\"setting-field\">\n                        <ul class=\"fetch-parameters-referencing-unauthorized-components\"></ul>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n    ");
      out.write("\n    <div id=\"fetch-parameters-permissions-parameter-contexts-message\" class=\"ellipsis fetch-parameters-dialog-message hidden\">\n        You do not have permissions to modify one or more synced parameter contexts.\n    </div>\n    <div id=\"fetch-parameters-permissions-affected-components-message\" class=\"ellipsis fetch-parameters-dialog-message hidden\">\n        You do not have permissions to modify one or more affected components.\n    </div>\n    <div id=\"fetch-parameters-missing-context-name-message\" class=\"ellipsis fetch-parameters-dialog-message hidden\">\n        Missing parameter context name.\n    </div>\n    <div class=\"fetch-parameters-canceling hidden unset\">\n        Canceling...\n    </div>\n</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
