/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.partials.canvas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class flowfile_002ddetails_002ddialog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<div id=\"flowfile-details-dialog\" layout=\"column\" class=\"hidden large-dialog\">\n    <div id=\"flowfile-details-dialog-content\" class=\"dialog-content\">\n        <div id=\"flowfile-details-tabs\" class=\"tab-container\"></div>\n        <div id=\"flowfile-details-tabs-content\">\n            <div id=\"flowfile-details-tab-content\" class=\"details-tab\">\n                <span id=\"flowfile-uri\" class=\"hidden\"></span>\n                <span id=\"flowfile-cluster-node-id\" class=\"hidden\"></span>\n                <div class=\"settings-left\">\n                    <div id=\"flowfile-details\">\n                        <div class=\"flowfile-header\">FlowFile Details</div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">UUID</div>\n                            <div id=\"flowfile-uuid\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">Filename</div>\n");
      out.write("                            <div id=\"flowfile-filename\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">File Size</div>\n                            <div id=\"flowfile-file-size\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">Queue Position</div>\n                            <div id=\"flowfile-queue-position\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">Queued Duration</div>\n                            <div id=\"flowfile-queued-duration\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">Lineage Duration</div>\n                            <div id=\"flowfile-lineage-duration\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"detail-name\">Penalized</div>\n                            <div id=\"flowfile-penalized\" class=\"detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div id=\"additional-flowfile-details\"></div>\n                    </div>\n                </div>\n                <div class=\"spacer\">&nbsp;</div>\n                <div class=\"settings-right\">\n                    <div id=\"flowfile-with-no-content\" class=\"content-details\">\n                        <div class=\"flowfile-header\">Content Claim</div>\n                        <div class=\"flowfile-info unset\">No Content Available</div>\n");
      out.write("                    </div>\n                    <div id=\"flowfile-content-details\" class=\"content-details\">\n                        <div class=\"flowfile-header\">Content Claim</div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"content-detail-name\">Container</div>\n                            <div id=\"content-container\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"content-detail-name\">Section</div>\n                            <div id=\"content-section\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"content-detail-name\">Identifier</div>\n                            <div id=\"content-identifier\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n");
      out.write("                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"content-detail-name\">Offset</div>\n                            <div id=\"content-offset\" class=\"content-detail-value\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div class=\"content-detail-name\">Size</div>\n                            <div id=\"content-size\" class=\"content-detail-value\"></div>\n                            <div id=\"content-bytes\" class=\"content-detail-value hidden\"></div>\n                            <div class=\"clear\"></div>\n                        </div>\n                        <div class=\"flowfile-detail\">\n                            <div id=\"content-download\" class=\"secondary-button fa fa-download button-icon\"><span>Download</span></div>\n                            <div id=\"content-view\" class=\"secondary-button fa fa-eye button-icon hidden\"><span>View</span></div>\n");
      out.write("                            <div class=\"clear\"></div>\n                        </div>\n                    </div>\n                </div>\n                <div class=\"clear\"></div>\n            </div>\n            <div id=\"flowfile-attributes-tab-content\" class=\"details-tab\">\n                <div id=\"flowfile-attributes-details\">\n                    <div id=\"flowfile-attributes-header\" class=\"flowfile-header\">Attribute Values</div>\n                    <div class=\"clear\"></div>\n                    <div id=\"flowfile-attributes-container\"></div>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
