/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.partials.canvas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class process_002dgroup_002dconfiguration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<div id=\"process-group-configuration\">\n    <div id=\"process-group-configuration-header-text\" class=\"settings-header-text\">Process Group Configuration</div>\n    <div class=\"settings-container\">\n        <div>\n            <div id=\"process-group-configuration-tabs\" class=\"settings-tabs tab-container\"></div>\n            <div class=\"clear\"></div>\n        </div>\n        <div id=\"process-group-configuration-tabs-content\">\n            <button id=\"add-process-group-configuration-controller-service\" class=\"add-button fa fa-plus\" title=\"Create a new controller service\"></button>\n            <div id=\"general-process-group-configuration-tab-content\" class=\"configuration-tab\">\n                <div id=\"general-process-group-configuration\">\n                    <div class=\"settings-columns\">\n                        <div class=\"settings-column\">\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Process group name</div>\n                                <span id=\"process-group-id\" class=\"hidden\"></span>\n");
      out.write("                                <div class=\"editable setting-field\">\n                                    <input type=\"text\" id=\"process-group-name\" class=\"setting-input\"/>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-name\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Process group parameter context</div>\n                                <div class=\"editable setting-field\">\n                                    <div id=\"process-group-parameter-context-combo\"></div>\n                                    <div id=\"parameter-contexts-recursive-container\">\n                                        <div id=\"parameter-contexts-recursive\" class=\"nf-checkbox checkbox-unchecked\"></div>\n                                        <div class=\"nf-checkbox-label\">Apply recursively</div>\n");
      out.write("                                        <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"When checked Parameter Context will be applied to the Process Group and all the embedded Process Groups recursively, if the user has the proper permissions on all the respective components. If the user does not have the proper permissions on any embedded Process Group, then the Parameter Context will not be applied for any components.\"></div>\n                                    </div>\n                                    <div class=\"clear\"></div>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-parameter-context\" class=\"unset\">Unauthorized</span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Execution Engine</div>\n                                <div class=\"editable setting-field\">\n");
      out.write("                                    <div id=\"process-group-execution-engine-combo\"></div>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-execution-engine\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div id=\"stateless-group-options\" class=\"setting\">\n                                <div class=\"setting\">\n                                    <div class=\"setting-name\">Max Concurrent Tasks</div>\n                                    <div class=\"editable setting-field\">\n                                        <input type=\"text\" id=\"process-group-max-concurrent-tasks\" class=\"setting-input\"/>\n                                    </div>\n                                    <div class=\"read-only setting-field\">\n                                        <span id=\"read-only-process-group-max-concurrent-tasks\" class=\"unset\"></span>\n");
      out.write("                                    </div>\n                                </div>\n                                <div class=\"setting\">\n                                    <div class=\"setting-name\">Stateless Flow Timeout</div>\n                                    <div class=\"editable setting-field\">\n                                        <input type=\"text\" id=\"process-group-stateless-flow-timeout\" class=\"setting-input\"/>\n                                    </div>\n                                    <div class=\"read-only setting-field\">\n                                        <span id=\"read-only-process-group-stateless-flow-timeout\" class=\"unset\"></span>\n                                    </div>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Process group FlowFile concurrency</div>\n                                <div class=\"editable setting-field\">\n                                    <div id=\"process-group-flowfile-concurrency-combo\"></div>\n");
      out.write("                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-flowfile-concurrency\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Process group outbound policy</div>\n                                <div class=\"editable setting-field\">\n                                    <div id=\"process-group-outbound-policy-combo\"></div>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-outbound-policy\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                        </div>\n                        <div class=\"settings-column\">\n                            <div class=\"setting\">\n");
      out.write("                                <div class=\"setting-name\">Default FlowFile Expiration\n                                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"This setting applies as the default FLowFile expiration for any new connection. Configuration of existing connections is unaffected.\"></div>\n                                </div>\n                                <div class=\"editable setting-field\">\n                                    <input type=\"text\" id=\"process-group-default-flowfile-expiration\" class=\"setting-input\"/>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-default-flowfile-expiration\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Default Back Pressure Object Threshold\n                                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"This setting applies as the default back pressure object count for any new connection. Configuration of existing connections is unaffected.\"></div>\n");
      out.write("                                </div>\n                                <div class=\"editable setting-field\">\n                                    <input type=\"text\" id=\"process-group-default-back-pressure-object-threshold\" class=\"setting-input\"/>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-default-back-pressure-object-threshold\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Default Back Pressure Data Size Threshold\n                                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"This setting applies as the default back pressure data size for any new connection. Configuration of existing connections is unaffected.\"></div>\n                                </div>\n                                <div class=\"editable setting-field\">\n");
      out.write("                                    <input type=\"text\" id=\"process-group-default-back-pressure-data-size-threshold\" class=\"setting-input\"/>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-default-back-pressure-data-size-threshold\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                            <div class=\"setting\">\n                                <div class=\"setting-name\">Log File Suffix\n                                    <div class=\"fa fa-question-circle\" alt=\"Info\" title=\"Turns on dedicated logging. When left empty log messages will be logged only to the primary app log. When set messages logged by components in this group will be sent to the standard app log, as well as a separate log file, with the provided name, specific to this group.\"></div>\n                                </div>\n                                <div class=\"editable setting-field\">\n");
      out.write("                                    <input type=\"text\" id=\"process-group-log-file-suffix\" class=\"setting-input\"/>\n                                </div>\n                                <div class=\"read-only setting-field\">\n                                    <span id=\"read-only-process-group-log-file-suffix\" class=\"unset\"></span>\n                                </div>\n                            </div>\n                        </div>\n                    </div>\n                </div>\n                <div class=\"setting\">\n                    <div class=\"setting-name\">Process group comments</div>\n                    <div class=\"editable setting-field\">\n                        <textarea id=\"process-group-comments\" class=\"setting-input\"></textarea>\n                    </div>\n                    <div class=\"read-only setting-field\">\n                        <span id=\"read-only-process-group-comments\" class=\"unset\"></span>\n                    </div>\n                </div>\n\n                <div class=\"editable settings-buttons\">\n");
      out.write("                    <div id=\"process-group-configuration-save\" class=\"button\">Apply</div>\n                    <div class=\"clear\"></div>\n                </div>\n            </div>\n            <div id=\"process-group-controller-services-tab-content\" class=\"configuration-tab\">\n                <div id=\"process-group-controller-services-table\" class=\"settings-table\"></div>\n            </div>\n        </div>\n    </div>\n    <div id=\"process-group-refresh-container\">\n        <button id=\"process-group-configuration-refresh-button\" class=\"refresh-button pointer fa fa-refresh\" title=\"Refresh\"></button>\n        <div class=\"last-refreshed-container\">\n            Last updated:&nbsp;<span id=\"process-group-configuration-last-refreshed\" class=\"last-refreshed\"></span>\n        </div>\n        <div id=\"process-group-configuration-loading-container\" class=\"loading-container\"></div>\n        <div id=\"flow-cs-availability\" class=\"hidden\">Listed services are available to all descendant Processors and services of this Process Group.</div>\n");
      out.write("        <div class=\"clear\"></div>\n    </div>\n</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
