/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/10.0.17
 * Generated at: 2023-10-26 22:18:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class canvas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>NiFi</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/nifi16.ico\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/reset.css/reset.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/nf-canvas-all.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/message-pane.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nf-common-ui.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/codemirror/lib/codemirror.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/codemirror/addon/hint/show-hint.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/nfeditor/jquery.nfeditor.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/nfeditor/languages/nfeditor.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/tabbs/jquery.tabbs.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/combo/jquery.combo.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/propertytable/jquery.propertytable.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/tagcloud/jquery.tagcloud.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/modal/jquery.modal.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"js/jquery/statusbar/jquery.statusbar.css?2.0.0-SNAPSHOT\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/qtip2/dist/jquery.qtip.min.css?\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/jquery-ui-dist/jquery-ui.min.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/jquery-minicolors/jquery.minicolors.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/slickgrid/slick.grid.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/slick-nifi-theme.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"fonts/flowfont/flowfont.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/angular-material/angular-material.min.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/font-awesome/css/font-awesome.min.css\" type=\"text/css\" />\n");
      out.write("        <script>\n");
      out.write("            //force browsers to use URLSearchParams polyfill do to bugs and inconsistent browser implementations\n");
      out.write("            URLSearchParams = undefined;\n");
      out.write("        </script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/url-search-params/build/url-search-params.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/codemirror/lib/codemirror-compressed.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/d3/dist/d3.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/jquery/dist/jquery.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/jquery-ui-dist/jquery-ui.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/jquery.base64.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/jquery.center.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/jquery.ellipsis.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/jquery.each.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/jquery.tab.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/jquery-form/jquery.form.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/tabbs/jquery.tabbs.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/combo/jquery.combo.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/modal/jquery.modal.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/jquery-minicolors/jquery.minicolors.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/lodash/lodash.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/moment/min/moment.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/qtip2/dist/jquery.qtip.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/lib/jquery.event.drag-2.3.0.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/plugins/slick.cellrangeselector.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/plugins/slick.cellselectionmodel.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/plugins/slick.rowselectionmodel.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/plugins/slick.autotooltips.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/slick.formatters.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/slick.editors.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/slick.dataview.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/slick.core.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/slickgrid/slick.grid.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular/angular.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-messages/angular-messages.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-resource/angular-resource.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-route/angular-route.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-aria/angular-aria.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-animate/angular-animate.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/angular-material/angular-material.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/JSON2/json2.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/nf/nf-namespace.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/nf/nf-ng-namespace.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/nf/canvas/nf-ng-canvas-namespace.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/nf/canvas/nf-canvas-all.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/nfeditor/languages/nfel.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/nfeditor/languages/nfpr.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/nfeditor/jquery.nfeditor.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/propertytable/jquery.propertytable.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/tagcloud/jquery.tagcloud.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery/statusbar/jquery.statusbar.js?2.0.0-SNAPSHOT\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body ng-controller=\"ngCanvasAppCtrl\" id=\"canvas-body\">\n");
      out.write("        <div id=\"splash\">\n");
      out.write("            <div id=\"splash-img\" layout=\"row\" layout-align=\"center center\">\n");
      out.write("                <md-progress-circular md-mode=\"indeterminate\" class=\"md-warn\" md-diameter=\"150\"></md-progress-circular>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/message-pane.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/banners-main.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/canvas-header.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/flow-status.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/about-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/ok-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/yes-no-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/status-history-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/search-users-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/disable-controller-service-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/enable-controller-service-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/fetch-parameters-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-controller-service-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-reporting-task-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-flow-analysis-rule-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-parameter-provider-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-parameter-context-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-processor-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-port-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-process-group-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-remote-process-group-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-template-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/upload-template-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/instantiate-template-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/fill-color-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/connections-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/save-flow-version-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/import-flow-version-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/revert-local-changes-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/show-local-changes-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/registry-configuration-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/new-registry-client-dialog.jsp", out, false);
      out.write("\n");
      out.write("        <div id=\"canvas-container\" class=\"unselectable\"></div>\n");
      out.write("        <div id=\"canvas-tooltips\">\n");
      out.write("            <div id=\"processor-tooltips\"></div>\n");
      out.write("            <div id=\"port-tooltips\"></div>\n");
      out.write("            <div id=\"process-group-tooltips\"></div>\n");
      out.write("            <div id=\"remote-process-group-tooltips\"></div>\n");
      out.write("            <div id=\"connection-tooltips\"></div>\n");
      out.write("        </div>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/navigation.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/settings-content.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/parameter-contexts-content.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/shell.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/controller-service-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/reporting-task-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/flow-analysis-rule-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/parameter-provider-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/processor-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/processor-details.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/process-group-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/override-policy-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/policy-management.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/remote-process-group-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/remote-process-group-details.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/remote-process-group-ports.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/remote-port-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/port-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/port-details.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/label-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/connection-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/drop-request-status-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/flowfile-details-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/listing-request-status-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/verification-request-status-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/referenced-attributes-configuration.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/queue-listing.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/component-state-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/canvas/component-version-dialog.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/partials/connection-details.jsp", out, false);
      out.write("\n");
      out.write("        <div id=\"context-menu\" class=\"context-menu unselectable\"></div>\n");
      out.write("        <span id=\"nifi-content-viewer-url\" class=\"hidden\"></span>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
