class CompositeKey:
    def __init__(self, col1_value, col2_value, col3_value, col4_value, col5_value):
        self.col1_value = col1_value
        self.col2_value = col2_value
        self.col3_value = col3_value
        self.col4_value = col4_value
        self.col5_value = col5_value

    def __hash__(self):
        return hash((self.col1_value, self.col2_value, self.col3_value, self.col4_value, self.col5_value))

    def __eq__(self, other):
        if not isinstance(other, type(self)):
            return NotImplemented
        return (self.col1_value, self.col2_value, self.col3_value, self.col4_value, self.col5_value) == \
               (other.col1_value, other.col2_value,
                other.col3_value, other.col4_value, other.col5_value)


composite_key1API = CompositeKey("Game Roster",
                                 "Player Profile",
                                 "Team Profile",
                                 "Team Roster",
                                 "Game Boxscore",
                                 "Play By Play",
                                 "Push Events",
                                 "Push Pulse",
                                 "Draft Summary",
                                 "Current Week Schedule",
                                 "Game Statistics",
                                 "League Hierarchy",
                                 "Prospects",
                                 "Season Schedule",
                                 "Team Draft Summary",
                                 "Top Prospects",
                                 "Trades",
                                 "Weekly Schedule",
                                 "Current Season Schedule",
                                 "Push Statistics",
                                 "Seasonal Statistics",
                                 "Daily Change Log",
                                 "Seasons",
                                 "Push Draft Picks",
                                 "Push Draft Trades",
                                 "Postgame Standings",
                                 "Weekly Depth Charts",
                                 "Weekly Injuries",
                                 "Daily Transactions",
                                 "Schedule",
                                 "Push Trades"
                                 )
composite_key2table = CompositeKey("PlayerDCIINFO",
                                   "PlayStats",
                                   "VenuInfo",
                                   "BoxscoreInfo",
                                   "GameStatTeamInfo",
                                   "GameStatPlayerInfo",
                                   "SeasonStatTeamInfo",
                                   "SeasonStatPlayerInfo",
                                   "SeasonStatOppoInfo",
                                   "LeagueInfo",
                                   "FranchiseInfo",
                                   "TeamInfo",
                                   "DraftInfo",
                                   "GameInfo",
                                   "PlaybyPlayInfo",
                                   "PlayPulse",
                                   "TransactionInfo",
                                   "GameStatTeamSummaryInfo",
                                   "StandingsInfo",
                                   "MetadataInfo",
                                   )

composite_key3element = CompositeKey(
    "player",
    "extra_point",
    "venue",
    "game",
    "passing",
    "receiving",
    "league",
    "team",
    "conference",
    "division",
    "franchise",
    "overtime",
    "away",
    "quarter",
    "home",
    "location",
    "possession",
    "start_location",
    "end_location",
    "from_team",
    "to_team",
    "team_color",
    "item",
    "official",
    "defense",
    "field_goal",
    "pass",
    "conversion",
    "defense_conversi on",
    "down_conversion",
    "kick",
    "punt",
    "rush",
    "thirddown",
    "fourthdown",
    "goaltogo",
    "redzone",
    "kicks",
    "field_goals",
    "punts",
    "rushing",
    "extra_points",
    "int_returns",
    "kick_returns",
    "punt_returns",
    "scoring",
    "play",
    "score",
    "pulse",
    "prospect",
    "misc_returns",
    "block",
    "rgb_color",
    "receive",
    "detail",
    "first_down",
    "return",
    "details",
    "record",
    "broadcast",
    "rank",
    "situation",
    "event",
    "end_situation",
    "start_situation",
    "type",
    "pick",
    "trade",
    "weather",
    "drive",
    "conversions",
    "streak",
    "transaction",
    "primary",
    "description",
    "penalty",
    "wind",
    "metadata",
    "season",
    "draft",
    "round",
    "changelog",
    "transactions",
    "kickoffs",
    "fumbles",
    "penalties",
    "coach",
    "fumble",
    "touchdowns",
    "statistics",
    "week",
    "defensive_team",
    "offensive_team",
    "period",
    "points-after- play",
    "event_context",
    "interceptions",
    "position",
    "kickj",
    "first_downs",
    "coin_toss",
    "future_pick",
    "game_clock",
    "strength-of-schedule",
    "strength-of-victory",
    "practice",
    "injury"
)


composite_key4attribute = CompositeKey("abbr_name",
                                       "aborted",
                                       "address",
                                       "attendance",
                                       "age",
                                       "air_yards",
                                       "alias",
                                       "away_points",
                                       "points",
                                       "alpha",
                                       "amount",
                                       "assignment",
                                       "assists",
                                       "ast_sacks",
                                       "ast_tackle",
                                       "ast_tlost",
                                       "att_yards",
                                       "attempt",
                                       "attempts",
                                       "attempts_19",
                                       "attempts_29",
                                       "attempts_39",
                                       "attempts_49",
                                       "attempts_50",
                                       "home_points",
                                       "avg_gain",
                                       "avg_hang_time",
                                       "avg_net_yards",
                                       "avg_pocket_time",
                                       "avg_yards",
                                       "batted_pass",
                                       "batted_passes",
                                       "birth_date",
                                       "birth_place",
                                       "blitz",
                                       "blitzes",
                                       "blk_fg_touchdowns",
                                       "blk_punt_touchdow ns",
                                       "blk_punt_touchdown s",
                                       "block",
                                       "blocked",
                                       "blue",
                                       "broken_tackles",
                                       "capacity",
                                       "id",
                                       "catchable",
                                       "catchable_passes",
                                       "category",
                                       "number",
                                       "channel",
                                       "city",
                                       "sequence",
                                       "clinched",
                                       "clock",
                                       "cmp_pct",
                                       "code",
                                       "college",
                                       "college_conf",
                                       "combined",
                                       "compensatory",
                                       "complete",
                                       "completions",
                                       "condition",
                                       "conference",
                                       "conference_game",
                                       "conversion_type",
                                       "country",
                                       "coverage",
                                       "created_at",
                                       "decision",
                                       "def_comp",
                                       "def_comps",
                                       "def_target",
                                       "def_targets",
                                       "defended_passes",
                                       "defense_attempts",
                                       "defense_successes",
                                       "deleted",
                                       "depth",
                                       "desc",
                                       "Description",
                                       "direction",
                                       "division",
                                       "down",
                                       "downed",
                                       "draft",
                                       "dropped",
                                       "dropped_passes",
                                       "name",
                                       "duration",
                                       "effective_date",
                                       "end_clock",
                                       "end_date",
                                       "end_reason",
                                       "end_time",
                                       "endzone",
                                       "game_number",
                                       "entry_mode",
                                       "event_category",
                                       "event_type",
                                       "experience",
                                       "ez_rec_tds",
                                       "ez_rec_touchdowns",
                                       "faircatch",
                                       "faircatches",
                                       "fake_field_goals",
                                       "fake_punts",
                                       "fg_return_touchdow ns",
                                       "fg_return_touchdowns",
                                       "first_downs",
                                       "first_drive_yardline",
                                       "first_name",
                                       "first_touch",
                                       "firstdown",
                                       "forced",
                                       "forced_fumble",
                                       "forced_fumbles",
                                       "fourth_down_stops",
                                       "full_name",
                                       "fumble",
                                       "fumble_recoveries",
                                       "fumble_return",
                                       "fumbles",
                                       "gain",
                                       "game_type",
                                       "games_played",
                                       "games_started",
                                       "goaltogo",
                                       "green",
                                       "gross_yards",
                                       "hang_time",
                                       "hash_mark",
                                       "height",
                                       "hex_color",
                                       "high_school",
                                       "sr_id",
                                       "huddle",
                                       "internet",
                                       "humidity",
                                       "hurries",
                                       "hurry",
                                       "network",
                                       "satellite",
                                       "in_game_status",
                                       "incompletion_type",
                                       "inside_20",
                                       "int_return",
                                       "int_touchdown",
                                       "int_touchdowns",
                                       "int_yards",
                                       "interception",
                                       "interceptions",
                                       "jersey",
                                       "kick_return",
                                       "kickoffs",
                                       "kneel_down",
                                       "kneel_downs",
                                       "knockdown",
                                       "knockdowns",
                                       "last_drive_yardline",
                                       "last_modified",
                                       "last_name",
                                       "lat",
                                       "lateral",
                                       "league",
                                       "league_id",
                                       "left_tightends",
                                       "length",
                                       "lng",
                                       "locale",
                                       "longest",
                                       "longest_touchdown",
                                       "losses",
                                       "lost",
                                       "lost_fumbles",
                                       "made",
                                       "made_19",
                                       "made_29",
                                       "made_39",
                                       "made_49",
                                       "made_50",
                                       "market",
                                       "match",
                                       "men_in_box",
                                       "misc_assists",
                                       "misc_foced_fumble s",
                                       "misc_foced_fumbles",
                                       "misc_forced_fumble s",
                                       "misc_fumble_recov eries",
                                       "misc_fumble_recove ries",
                                       "misc_fumble_recover ies",
                                       "misc_tackles",
                                       "missed",
                                       "missed_tackles",
                                       "scheduled",
                                       "status",
                                       "title",
                                       "name_suffix",
                                       "net_attempts",
                                       "net_yards",
                                       "temp",
                                       "neutral_site",
                                       "no_attempt",
                                       "no_play",
                                       "nullified",
                                       "speed",
                                       "on_target_throw",
                                       "on_target_throws",
                                       "onside",
                                       "onside_attempt",
                                       "onside_attempts",
                                       "onside_success",
                                       "onside_successes",
                                       "operation",
                                       "opp_rec",
                                       "opp_rec_td",
                                       "opp_rec_tds",
                                       "opp_rec_yards",
                                       "other",
                                       "out_of_bounds",
                                       "outcome",
                                       "overall",
                                       "own_rec",
                                       "own_rec_td",
                                       "own_rec_tds",
                                       "own_rec_yards",
                                       "participant",
                                       "pass",
                                       "pass_attempts",
                                       "pass_defended",
                                       "pass_route",
                                       "pass_successes",
                                       "passes_defended",
                                       "pat_points_attempt ed",
                                       "pct",
                                       "penalties",
                                       "penalty",
                                       "penalty_type",
                                       "penalty_yards",
                                       "play_action",
                                       "play_category",
                                       "play_count",
                                       "play_direction",
                                       "play_id",
                                       "play_type",
                                       "players_rushed",
                                       "pocket_location",
                                       "pocket_time",
                                       "points_against",
                                       "points_for",
                                       "poor_throws",
                                       "position",
                                       "possession_time",
                                       "preferred_name",
                                       "primary",
                                       "publishable",
                                       "punt_return",
                                       "qb_at_snap",
                                       "qb_hit",
                                       "qb_hits",
                                       "quarter",
                                       "rating",
                                       "reason_missed",
                                       "receive_attempts",
                                       "receive_successes",
                                       "reception",
                                       "receptions",
                                       "red",
                                       "redzone_attempts",
                                       "redzone_targets",
                                       "remaining_challenges",
                                       "remaining_timeouts",
                                       "result",
                                       "return",
                                       "return_yards",
                                       "returned",
                                       "returns",
                                       "review_type",
                                       "right_tightends",
                                       "role",
                                       "roof_type",
                                       "round",
                                       "run_pass_option",
                                       "running",
                                       "running_lane",
                                       "rush",
                                       "rush_attempts",
                                       "rush_plays",
                                       "rush_successes",
                                       "sack",
                                       "sack_split",
                                       "sack_yards",
                                       "sacks",
                                       "safeties",
                                       "safety",
                                       "scoring_drive",
                                       "scoring_play",
                                       "scramble",
                                       "scrambles",
                                       "screen_pass",
                                       "season_id",
                                       "seconds",
                                       "type",
                                       "year",
                                       "sos",
                                       "source",
                                       "source_id",
                                       "sov",
                                       "sp_assists",
                                       "sp_blocks",
                                       "sp_forced_fumbles",
                                       "sp_fumble_recoveri es",
                                       "sp_fumble_recoverie s",
                                       "sp_tackles",
                                       "spikes",
                                       "squib_kick",
                                       "squib_kicks",
                                       "start_clock",
                                       "start_date",
                                       "start_reason",
                                       "start_time",
                                       "state",
                                       "status_after",
                                       "status_before",
                                       "status_date",
                                       "successes",
                                       "supplemental",
                                       "surface",
                                       "tackle",
                                       "tackles",
                                       "target",
                                       "targets",
                                       "team",
                                       "team_name",
                                       "team_sequence",
                                       "tfd",
                                       "three_and_outs_forc ed",
                                       "throw_aways",
                                       "ties",
                                       "time",
                                       "tloss",
                                       "tloss_yards",
                                       "tlost",
                                       "tlost_yards",
                                       "top_prospect",
                                       "total",
                                       "total_endzone",
                                       "total_return",
                                       "total_yards",
                                       "touchback",
                                       "touchbacks",
                                       "touchdown",
                                       "touchdowns",
                                       "trade_date",
                                       "traded",
                                       "transaction_code",
                                       "transaction_type",
                                       "transaction_year",
                                       "turnover_successes",
                                       "turnovers",
                                       "updated_at",
                                       "used_challenges",
                                       "used_timeouts",
                                       "version",
                                       "wall_clock",
                                       "weight",
                                       "win_pct",
                                       "wins",
                                       "yardline",
                                       "yards",
                                       "yards_after_catch",
                                       "yards_after_contac t",
                                       "yards_after_contact",
                                       "yfd",
                                       "zip")

composite_key5font = CompositeKey("String",
                                  "Integer",
                                  "Decimal",
                                  "Boolean",
                                  "GUID",
                                  "Date/Time",
                                  "Date",
                                  "Double",
                                  )

data_dict = {
    composite_key1: dataset1,
    composite_key2: dataset2
}

if composite_key1 in data_dict:
    print("Dataset with composite_key1 exists.")
